import type {
  CardType,
  FuelAssignmentType,
  FuelCardKind,
  FuelCardStatus,
  PrismaClient,
} from '../../generated/prisma/client';

type CardSeed = {
  readonly cardNumber: string;
  readonly type: CardType;
  readonly companyId: number;
  readonly userId: null;
  readonly isActive: boolean;
  readonly fuelName: string | null;
  readonly fuelCardKind: FuelCardKind;
  readonly fuelGroup: string;
  readonly fuelAssignmentType: FuelAssignmentType;
  readonly fuelStatus: FuelCardStatus;
};

const cards: readonly CardSeed[] = [
  // ── Alianza Eléctrica (companyId: 1) ─────────────────────────────────────
  {
    cardNumber: '6363180032194970',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'MOTOITALA OPE ATIZAPAN',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032194993',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'VTAS SLP ALEJANDRO TENO',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032195016',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'JEPP JUAN ORTIZ',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221465',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'VERSA UTILITARIO MTY',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221473',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'KIA RIO VTAS UTI SLP',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221481',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN NP300 OPERACIONESPUE',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221499',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'VERSA GERENCIA DE VTAS MTY',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221507',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'FORD DUTY F350 MTY',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221515',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'VERSA UTILITARIO QUERETARO',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221523',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'VERSA UTILITARIO PUEBLA',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221531',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN VDRIVE MONTERREY',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221549',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN NP 300 OPERACIONES SLP',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221556',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'HYUNDAI OPERACIONES MTY',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221564',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'FORD F350 OPERACIONES QRO',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221572',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN NP300 ALMACEN SLP',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221580',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN VDRIVE MONTERREY',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221598',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN NP 300 OPERACIONES MTY',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221606',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN VERSAUTILITARIO VTAS QR',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221614',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'FORD F350 OPERCIONES ATIZAPAN',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221622',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'VERSA GERENCIA DE VTAS LEON',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221630',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'VOLKSWAGEN DELIVERY ATIZAPAN',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221655',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'DODGE RAM 400 OPERACIONES SLP',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221663',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'VERSA GERENCIA DE VTAS LEON',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221671',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN NP 300 OPERACIONES QRO',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221689',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'GM AVEOUTILITARIO VTAS PUEBLA',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221697',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN NP 300 OPERACIONES LEON',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221705',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'FORD F350 OPERCIONES LEON',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221713',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSANV DRIVE LINO SLP',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221721',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NP300 MONTERREY',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221739',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: null,
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221747',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN V DRIVE MONTERRET',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAGS - CONTROLES',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032976001',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'TRANSIT ATIZAPAN',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032976019',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN NP ATIZAPAN',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032976027',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN V DRIVE MANUEL ATIZ',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032976035',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN V DRIVE UTI ATIZAPAN',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032976043',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'TRANSIT ATIZ',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032195024',
    type: 'FUEL',
    companyId: 1,
    userId: null,
    isActive: true,
    fuelName: 'Tarjeta Alianza VW delivery 2026',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },

  // ── FGE (companyId: 2) ───────────────────────────────────────────────────
  {
    cardNumber: '6363180032366864',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'HONDA HORACIO ATIZAPAN',
    fuelCardKind: 'physical',
    fuelGroup: 'COMODIN TARJETA',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032366872',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN KIVS PROPIO LILEANA CAN',
    fuelCardKind: 'physical',
    fuelGroup: 'COMODIN TARJETA',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032366880',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'COMODIN VENTAS FGE',
    fuelCardKind: 'physical',
    fuelGroup: 'COMODIN TARJETA',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378844',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'FREIGHTLINEOPEATI',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378851',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'VOLKSWAGEN DIRECCION ATIZ',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PREMIUM PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378869',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'FORD TRANSIT OPEATI',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378877',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'SUBURBAN DIRECCION',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PREMIUM PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378885',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'FORDDUTTY 350OPEATI',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378893',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'LINCOLNESPFERDIRECC',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PREMIUM PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378901',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN V JONATHAN PEREZ',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378919',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'MAZDACXCECIATIZAPA',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378927',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'NISSANVDIRECCION',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378935',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'VOLKSWAGENALBERTO',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378943',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'HYUNDAI EX8 ATIZAPAN',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378950',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'CADILLACDIRECCION',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PREMIUM PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378968',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'UNIDAD REASIGNADA A AEL',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378976',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'BMW 430 DIREC',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PREMIUM PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032378992',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'NISSANVDIRC HECTOR',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PREMIUM PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032379008',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'MERCEDESDIREC',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PREMIUM PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032379016',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'JETTA ARTURO CHAV',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032379024',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'NIISAN V DRIVE UTILITARIO',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032379032',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'NISSANVMONICAV',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA PLACA TANQUE KM - TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032819987',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'COMODIN',
    fuelCardKind: 'physical',
    fuelGroup: 'COMODIN TARJETA',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032819995',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'COMODIN',
    fuelCardKind: 'physical',
    fuelGroup: 'COMODIN TARJETA',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032820001',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN V DRIVE DIRECC',
    fuelCardKind: 'physical',
    fuelGroup: 'COMODIN TARJETA',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032820019',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'GOL ERCIK LECUONA ATIZA',
    fuelCardKind: 'physical',
    fuelGroup: 'COMODIN TARJETA',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032820027',
    type: 'FUEL',
    companyId: 2,
    userId: null,
    isActive: true,
    fuelName: 'BYD JOSE SILVEIRA',
    fuelCardKind: 'physical',
    fuelGroup: 'COMODIN TARJETA',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },

  // ── FG Manufacturing (companyId: 3) ──────────────────────────────────────
  {
    cardNumber: '6363180032194936',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'VOLKSWAGENVISTURALBER',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032194944',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'MAZDA CX30 PROPIA LUCY MORALES',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032194951',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'FG MANUFACTURING',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032194969',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN V DRIVE FGM',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221259',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'FREIGHTLINERTHORTOAT',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAG - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221267',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'FREIGHTLINETHOR',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAG - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221275',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'NISSANVPRODATIZAP',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAG - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032221283',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'THORTONFREIATIZ',
    fuelCardKind: 'virtual',
    fuelGroup: 'TAG',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032976134',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'HONDA H2V ALDO SERRANO',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032976142',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'COMODIN',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032976159',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'COMODIN',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032976167',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'COMODIN',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032976175',
    type: 'FUEL',
    companyId: 3,
    userId: null,
    isActive: true,
    fuelName: 'COMODIN',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },

  // ── Tableros y Arrancadores (companyId: 4) ────────────────────────────────
  {
    cardNumber: '6363180032194886',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'AVEO JOSE GALVAN ATIZAP',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032194894',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'MOTOCICLETA PROPIA RICARDO PER',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032194902',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'MG5 PROPIO LUIS DURAN',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032194928',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'NISSA V DRIVE JOSE JAVIER TALL',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032219121',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'VERSA VDRIVE CARLOSSANCHEZ MTR',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAG - CONTROLES',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032219139',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'MAZDA CX30 HIPACTIC ATIZAPAN',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAG - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032219147',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'HYUNDAI EX8 OPE ATIZAPA',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAG - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032219154',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'NISSAN NP 300 OPERACIONES QTRO',
    fuelCardKind: 'virtual',
    fuelGroup: 'DIESEL TAG - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032219162',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'REASIGNADO AEL',
    fuelCardKind: 'virtual',
    fuelGroup: 'MAGNA TAG - CONTROLES',
    fuelAssignmentType: 'NotAcumulative',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032858563',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'OPERACIONES',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032858571',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'EMILY AVILA GELVY',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032858589',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'AUTO PROPIO DAVID OMAR',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032858597',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'COMODIN',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },
  {
    cardNumber: '6363180032858605',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: true,
    fuelName: 'COMODIN',
    fuelCardKind: 'physical',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'active',
  },

  // ── Test / inactiva ───────────────────────────────────────────────────────
  {
    cardNumber: '4242424244242424',
    type: 'FUEL',
    companyId: 4,
    userId: null,
    isActive: false,
    fuelName: 'Tarjeta de Pruebas Sistemas - Borrar 3',
    fuelCardKind: 'virtual',
    fuelGroup: 'GRUPO DE TARJETAS BASE',
    fuelAssignmentType: 'Acumulable',
    fuelStatus: 'inactive',
  },
];

export async function seedFuelCards(
  prismaClient: PrismaClient,
): Promise<number> {
  let created = 0;

  for (const card of cards) {
    const existing = await prismaClient.card.findUnique({
      where: { cardNumber: card.cardNumber },
    });

    if (existing) {
      await prismaClient.card.update({
        where: { cardNumber: card.cardNumber },
        data: {
          companyId: card.companyId,
          isActive: card.isActive,
          fuelName: card.fuelName,
          fuelCardKind: card.fuelCardKind,
          fuelGroup: card.fuelGroup,
          fuelAssignmentType: card.fuelAssignmentType,
          fuelStatus: card.fuelStatus,
        },
      });
    } else {
      await prismaClient.card.create({ data: card });
      created++;
    }
  }

  return created;
}
